### ISSUE TITLE
Question: Why / when would you need this package?

### ISSUE THREAD

**Issue by connecteev** [YieldStudio/tailwind-merge-php#2]
I don't see a discussions section so opening an issue here instead.
I am confused as to why / when you would need this package. https://github.com/dcastil/tailwind-merge exists for JS.
When do you need to merge tailwind classes in PHP vs Javascript?

**Comment by maximerenou** [comment]
For PHP-generated front-end (like Blade templates) it may be useful

**Comment by JamesHemery** [comment]
Hi @connecteev,

I've enabled discussions section :) 

As @maximerenou says, it's for front-ends generated in PHP (blade, twig, ob template...), mainly in order to be able to develop reusable components without having to worry about the precedence problems known with tailwind.

**Comment by connecteev** [comment]
Makes sense, thanks @maximerenou @JamesHemery
